kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: localstorage-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
  selector: 
    matchLabels:
      kubernetes.io/hostname: kind-worker2
